name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "nitesh166k@gmail.com"
          git config --global user.name "Nitesh-loop"
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        run: |
          npm install -g gh-pages
          # Remove existing index.html (if it exists)
          rm -f index.html
          # Copy index.html from the main branch
          git checkout main -- index.html
          # Deploy to gh-pages branch
          gh-pages -d build -b gh-pages -u "Nitesh-loop <nitesh166k@gmail.com>" -t ${{ secrets.GH_PAT }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
