name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        run: |
          npm install -g gh-pages
          gh-pages -d build -b gh-pages -r https://github.com/Nitesh-loop/react-project-test.git
