name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        run: |
          npm install -g gh-pages
          git config --global credential.helper store
          echo "//github.com/:_authToken=${{ secrets.GH_PAT }}" > ~/.git-credentials
          gh-pages -d build -b gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
